export const COPY = {
  gallery: {
    kicker: 'Choose a universe',
    headline: 'Every universe has its codes.',
    subline: 'Pick where you belong. Then make it yours.',
    enter: 'Enter',
  },
  stage: {
    talk: 'Talk to her',
    send: 'Send',
    inputPlaceholder: 'Say something',
    leave: 'All universes',
    outOfTurns: 'That is the free encounter.',

    // Session setup: only what the user understands. Never a raw prompt.
    setSession: 'Set this session',
    sessionNote: 'These apply to this conversation only. Who she is does not change.',
    nickname: 'What should she call you?',
    nicknamePlaceholder: 'Name or nickname',
    scenario: 'What are you doing together?',
    mood: 'How should this feel?',
    style: 'How talkative should she be?',
    length: 'Reply length',
    voice: 'Her voice',
    resetSession: 'Reset',
    applySession: 'Apply',

    // Save gate: state what is kept, plainly. No pressure copy.
    saveTitle: 'Save this chapter',
    saveBody: 'This session is temporary. Save it so she can continue from here next time.',
    saveList: 'She will remember',
    saveCost: 'Costs 1 credit.',
    saveCta: 'Use 1 credit to save',
    saveSkip: 'Continue without saving',
    saveNothing: 'Nothing worth keeping yet. Talk a little longer.',
    noCredits: 'No credits left. The conversation still works without saving.',

    unlockTitle: 'Turn her around',
    unlockBody: 'The front arc is free to inspect. The full turntable comes with the figurine.',
    unlockCta: 'Use 1 credit',
    unlockCode: 'Or enter the code from your box',
    unlockCodeCta: 'Unlock',
    unlockSkip: 'Not now',
    badCode: 'That code does not match.',

    tabLook: 'Appearance',
    lookNote: 'Regenerate her look from a prompt. The sculpt stays on model.',
    lookPlaceholder: 'Moonlit palette, softer highlights.',
    lookGenerate: 'Regenerate look',
    lookRestore: 'Original look',
  },
  arrival: {
    headline: 'Every universe has its codes.',
    subline: 'Choose where you belong. Then make it yours.',
    cta: 'Enter Afterburn City',
    skip: 'Skip intro',
  },
  studio: {
    panelTitle: 'Make it yours',
    panelLead: 'Your Mate is regenerated from this character. Describe yourself, or drop in a photo.',
    textTab: 'Describe',
    photoTab: 'Photo',
    textPlaceholder: 'Layered black hair, round glasses, calm, smart casual.',
    photoHint: 'Stays on your device.',
    choosePhoto: 'Choose image',
    generate: 'Generate My Mate',
    processing: ['Reading your input', 'Re-sculpting the base', 'Painting the colorway'],
    baseNote: 'Base model locked to the collectible line.',
  },
  reveal: {
    kicker: 'Your Mate',
    namePlaceholder: 'Name your Mate',
    join: 'Join Afterburn City',
    back: 'Back to Studio',
  },
  joined: {
    headline: 'Welcome to Afterburn City.',
    subline: 'Yours, and unmistakably one of the line.',
    restart: 'Start over',
  },
  errors: {
    badImage: 'That file is not an image we can read. Try a JPG or PNG.',
    emptyInput: 'Describe yourself or add a photo first.',
    generic: 'Something glitched. Try again.',
  },
} as const;
