export const COPY = {
  gallery: {
    kicker: 'Chọn cách bắt đầu',
    headline: 'Anh muốn gặp một nhân vật, hay tạo Mate của riêng mình?',
    subline: 'Mỗi vũ trụ là một trải nghiệm khác nhau. Anh có thể quay lại bất cứ lúc nào.',
    enter: 'Bước vào',
  },
  stage: {
    talk: 'Nói chuyện với em',
    send: 'Gửi',
    inputPlaceholder: 'Viết gì đó cho em...',
    leave: 'Tất cả vũ trụ',
    outOfTurns: 'Không đủ credit cho lượt này.',

    // Session setup: only what the user understands. Never a raw prompt.
    setSession: 'Thiết lập cuộc trò chuyện',
    setSessionShort: 'Thiết lập',
    cardToggle: 'Hồ sơ',
    levelLabel: 'Em với anh',
    levelNext: 'Đi tiếp trong mạch truyện để em mở thêm một phần.',
    levelMax: 'Em đã kể hết với anh rồi.',
    voiceChat: 'Gọi cho em',
    voiceChatLocked: 'Sắp mở: nói trực tiếp với em bằng giọng của anh.',
    sessionNote: 'Thiết lập này chỉ áp dụng cho lần gặp này. Con người của em không đổi.',
    length: 'Độ dài phản hồi',
    identity: 'Anh muốn nhập vai ai?',
    identityPlaceholder: 'Tên nhân vật anh muốn trở thành',
    identityNote:
      'Trong lần gặp này, em nhận ra anh là chính nhân vật đó trong thế giới của em — cùng vũ khí, năng lực và quá khứ của họ, không phải một người đang cosplay. Nếu một chi tiết chưa rõ, em sẽ hỏi anh trong vai.',
    resetSession: 'Đặt lại',
    applySession: 'Xong',

    quest: 'Nhiệm vụ',
    questTitle: 'Nhiệm vụ câu chuyện',
    questLead: 'Cốt truyện mở ký ức của em; Tân thủ thưởng credit cho những thao tác đầu tiên.',
    questStart: 'Bắt đầu nhiệm vụ',
    questActive: 'Đang thực hiện',
    questDone: 'Đã hoàn thành',
    questLocked: 'Hoàn thành nhiệm vụ trước để mở tiếp.',
    questClose: 'Để sau',
    questReward: 'Mở câu chuyện',

    speakAs: 'Để em nói hộ',
    voiceMessageTitle: 'Để em nói hộ',
    voiceMessageLead: 'Nhập một câu ngắn. Em sẽ nói bằng giọng của mình.',
    voiceMessageLabel: 'Câu anh muốn em nói',
    voiceMessagePlaceholder: 'Ví dụ: Anh về nhà cẩn thận nhé.',
    voiceMessageSend: 'Cho em nói',
    voiceMessageFree: 'Mỗi câu tốn {cost} credit. Anh còn {count}.',
    voiceMessageCredits: 'Còn {count} lượt nói trả phí',
    voiceMessageEmpty: 'Anh hãy nhập câu muốn em nói.',
    voiceMessageNoCredits: 'Không đủ credit cho một câu nói. Nhập mã để nạp thêm.',
    voiceMessageClose: 'Đóng',
    walletTitle: 'Credit',
    walletNote: 'Mỗi thứ tốn credit đều ghi giá sẵn.',
    walletPrices: 'Nhắn 2 · Để em nói hộ 6 · Lưu chương 12 · Bàn xoay 30',
    walletRedeem: 'Nhập mã',
    walletRedeemCta: 'Nạp',
    walletRedeemOk: 'Đã nạp 50 credit.',
    walletRedeemBad: 'Mã không đúng.',
    personalVoiceTitle: 'Giọng riêng cho Mate',
    personalVoiceLead: 'Sắp ra mắt. Anh sẽ chọn chất giọng, nhịp nói và màu cảm xúc riêng cho Mate của mình.',
    personalVoiceNote: 'Không dùng để sao chép giọng người thật khi chưa xác minh chủ sở hữu.',

    // Save gate: state what is kept, plainly. No pressure copy.
    saveTitle: 'Lưu chương này',
    saveBody: 'Lần gặp này là tạm thời. Lưu lại để lần sau em tiếp tục từ đây.',
    saveList: 'Em sẽ nhớ',
    saveCost: 'Tốn 12 credit.',
    saveCta: 'Lưu chương · 12',
    saveSkip: 'Tiếp tục mà không lưu',
    saveNothing: 'Chưa có điều gì đáng giữ lại. Nói thêm với em một chút nhé.',
    noCredits: 'Không đủ credit để lưu. Cuộc trò chuyện vẫn tiếp tục được.',

    tabLook: 'Ngoại hình',
    lookNote: 'Tạo lại màu sắc theo mô tả. Dáng mô hình vẫn được giữ nguyên.',
    lookPlaceholder: 'Tông trăng đêm, ánh sáng dịu hơn.',
    lookGenerate: 'Tạo lại diện mạo',
    lookRestore: 'Khôi phục ban đầu',
  },
  persona: {
    title: 'Lần này anh muốn em ở bên anh thế nào?',
    note: 'Anh chỉnh cách em hiện diện trong phiên này; con người, canon và ranh giới của em không đổi.',
    tone: {
      label: 'Giọng em với anh',
      stops: ['Dịu dàng', 'Vừa phải', 'Thẳng thắn'],
    },
    problem: {
      label: 'Khi anh có chuyện',
      stops: ['Nghe anh trước', 'Cùng anh gỡ', 'Thách lại anh'],
    },
    energy: {
      label: 'Năng lượng',
      stops: ['Điềm tĩnh', 'Cân bằng', 'Sôi nổi'],
    },
    humor: {
      label: 'Hài hước',
      options: [
        { id: 'dry', label: 'Tỉnh khô' },
        { id: 'playful', label: 'Vui nhẹ' },
        { id: 'chaotic', label: 'Lầy một chút' },
        { id: 'minimal', label: 'Ít đùa' },
      ],
    },
    proactive: {
      label: 'Mức chủ động',
      stops: ['Khi anh gọi', 'Thỉnh thoảng', 'Thường xuyên'],
    },
    relationship: {
      label: 'Vai của em với anh',
      options: [
        { id: 'friend', label: 'Bạn' },
        { id: 'companion', label: 'Đồng hành' },
        { id: 'mentor', label: 'Dẫn dắt' },
        { id: 'rival', label: 'Đối thủ' },
        { id: 'custom', label: 'Khác…' },
      ],
      customPlaceholder: 'Ví dụ: người cùng anh giữ bí mật',
      customLabel: 'Vai khác của em với anh',
    },
    previewLabel: 'Lời dặn em sẽ dùng',
    overrideNote: 'Đang dùng bản chỉnh tay',
    advancedSummary: 'Nâng cao → Chỉnh tay lời dặn',
    advancedLabel: 'Lời dặn chỉnh tay cho em',
    advancedPlaceholder: 'Anh viết lời dặn riêng cho em trong phiên này.',
    restore: 'Khôi phục theo thanh trượt',
  },
  arrival: {
    headline: 'Mỗi vũ trụ đều có luật riêng.',
    subline: 'Chọn nơi anh thuộc về, rồi biến nó thành của anh.',
    cta: 'Vào Afterburn City',
    skip: 'Bỏ qua mở đầu',
  },
  studio: {
    panelTitle: 'Biến thành của anh',
    panelLead: 'Mate của anh được tạo từ nhân vật này. Hãy mô tả anh hoặc thêm một tấm ảnh.',
    textTab: 'Mô tả',
    photoTab: 'Ảnh',
    textPlaceholder: 'Tóc đen nhiều lớp, kính tròn, điềm tĩnh, ăn mặc gọn gàng.',
    photoHint: 'Ảnh chỉ ở trên thiết bị của anh.',
    choosePhoto: 'Chọn ảnh',
    generate: 'Tạo Mate của anh',
    processing: ['Đang đọc mô tả của anh', 'Đang tạo dáng nền', 'Đang phối màu'],
    baseNote: 'Mẫu nền thuộc dòng mô hình được giữ nguyên.',
  },
  reveal: {
    kicker: 'Mate của anh',
    namePlaceholder: 'Đặt tên cho Mate',
    join: 'Gia nhập Afterburn City',
    back: 'Về Studio',
  },
  joined: {
    headline: 'Chào mừng đến Afterburn City.',
    subline: 'Của anh, và không thể nhầm với bất kỳ ai trong dòng này.',
    restart: 'Bắt đầu lại',
  },
  errors: {
    badImage: 'Không thể đọc ảnh này. Hãy thử JPG hoặc PNG.',
    emptyInput: 'Hãy mô tả anh hoặc thêm ảnh trước.',
    generic: 'Có gì đó trục trặc. Anh thử lại nhé.',
  },
} as const;
