export const COPY = {
  gallery: {
    kicker: 'Chọn một vũ trụ',
    headline: 'Mỗi vũ trụ đều có luật riêng.',
    subline: 'Chọn nơi anh thuộc về, rồi biến nó thành của anh.',
    enter: 'Bước vào',
  },
  stage: {
    talk: 'Nói chuyện với em',
    send: 'Gửi',
    inputPlaceholder: 'Viết gì đó cho em...',
    leave: 'Tất cả vũ trụ',
    outOfTurns: 'Anh đã dùng hết 5 lượt trò chuyện miễn phí.',

    // Session setup: only what the user understands. Never a raw prompt.
    setSession: 'Thiết lập cuộc trò chuyện',
    sessionNote: 'Thiết lập này chỉ áp dụng cho lần gặp này. Con người của em không đổi.',
    nickname: 'Em nên gọi anh là gì?',
    nicknamePlaceholder: 'Tên hoặc biệt danh',
    scenario: 'Hai người đang làm gì cùng nhau?',
    mood: 'Anh muốn không khí thế nào?',
    style: 'Em nên chủ động đến đâu?',
    length: 'Độ dài phản hồi',
    voice: 'Giọng của em',
    persona: 'Cách em đồng hành với anh',
    personaPlaceholder: 'Ví dụ: trêu nhẹ, nói thẳng và nhớ hỏi về ngày của anh.',
    personaNote: 'Đây là gu trò chuyện của anh, không thay đổi ký ức hay bản chất của em.',
    resetSession: 'Đặt lại',
    applySession: 'Áp dụng',

    quest: 'Nhiệm vụ',
    questTitle: 'Nhiệm vụ câu chuyện',
    questLead: 'Hoàn thành một cuộc trò chuyện thật để mở thêm ký ức của em.',
    questStart: 'Bắt đầu nhiệm vụ',
    questActive: 'Đang thực hiện',
    questDone: 'Đã hoàn thành',
    questLocked: 'Hoàn thành nhiệm vụ trước để mở tiếp.',
    questClose: 'Để sau',
    questReward: 'Mở câu chuyện',

    speakAs: 'Để em nói hộ',
    voiceMessageTitle: 'Để em nói hộ',
    voiceMessageLead: 'Nhập một câu ngắn. Em sẽ nói bằng giọng của mình.',
    voiceMessageLabel: 'Câu anh muốn em nói',
    voiceMessagePlaceholder: 'Ví dụ: Anh về nhà cẩn thận nhé.',
    voiceMessageSend: 'Cho em nói',
    voiceMessageFree: 'Còn {count} lượt nói miễn phí',
    voiceMessageCredits: 'Còn {count} lượt nói trả phí',
    voiceMessageEmpty: 'Anh hãy nhập câu muốn em nói.',
    voiceMessageNoCredits: 'Anh đã dùng hết lượt miễn phí. Lượt nói trả phí sẽ mở cùng trang thanh toán.',
    voiceMessageClose: 'Đóng',
    voiceMessagePricing: 'Gói lượt nói trả phí',
    voiceMessagePricingNote: 'Thanh toán sẽ được bật sau khi kết nối trang thanh toán.',
    voiceMessageTopUp: 'Sắp mở',
    personalVoiceTitle: 'Giọng riêng cho Mate',
    personalVoiceLead: 'Sắp ra mắt. Anh sẽ chọn chất giọng, nhịp nói và màu cảm xúc riêng cho Mate của mình.',
    personalVoiceNote: 'Không dùng để sao chép giọng người thật khi chưa xác minh chủ sở hữu.',

    // Save gate: state what is kept, plainly. No pressure copy.
    saveTitle: 'Lưu chương này',
    saveBody: 'Lần gặp này là tạm thời. Lưu lại để lần sau em tiếp tục từ đây.',
    saveList: 'Em sẽ nhớ',
    saveCost: 'Tốn 1 lượt.',
    saveCta: 'Dùng 1 lượt để lưu',
    saveSkip: 'Tiếp tục mà không lưu',
    saveNothing: 'Chưa có điều gì đáng giữ lại. Nói thêm với em một chút nhé.',
    noCredits: 'Anh không còn lượt. Cuộc trò chuyện vẫn hoạt động nếu không lưu.',

    unlockTitle: 'Xoay em để ngắm',
    unlockBody: 'Anh có thể ngắm góc trước miễn phí. Toàn bộ góc xoay đi kèm mô hình.',
    unlockCta: 'Mở bàn xoay',
    unlockOwn: 'Tạo phiên bản của anh',
    unlockOwnNote: 'Một phiên bản do anh tạo, anh có thể xoay ngắm tự do.',
    unlockCode: 'Hoặc nhập mã trong hộp',
    unlockCodeCta: 'Mở khoá',
    unlockSkip: 'Để sau',
    badCode: 'Mã này không khớp.',

    tabLook: 'Ngoại hình',
    lookNote: 'Tạo lại màu sắc theo mô tả. Dáng mô hình vẫn được giữ nguyên.',
    lookPlaceholder: 'Tông trăng đêm, ánh sáng dịu hơn.',
    lookGenerate: 'Tạo lại diện mạo',
    lookRestore: 'Khôi phục ban đầu',
  },
  arrival: {
    headline: 'Mỗi vũ trụ đều có luật riêng.',
    subline: 'Chọn nơi anh thuộc về, rồi biến nó thành của anh.',
    cta: 'Vào Afterburn City',
    skip: 'Bỏ qua mở đầu',
  },
  studio: {
    panelTitle: 'Biến thành của anh',
    panelLead: 'Mate của anh được tạo từ nhân vật này. Hãy mô tả anh hoặc thêm một tấm ảnh.',
    textTab: 'Mô tả',
    photoTab: 'Ảnh',
    textPlaceholder: 'Tóc đen nhiều lớp, kính tròn, điềm tĩnh, ăn mặc gọn gàng.',
    photoHint: 'Ảnh chỉ ở trên thiết bị của anh.',
    choosePhoto: 'Chọn ảnh',
    generate: 'Tạo Mate của anh',
    processing: ['Đang đọc mô tả của anh', 'Đang tạo dáng nền', 'Đang phối màu'],
    baseNote: 'Mẫu nền thuộc dòng mô hình được giữ nguyên.',
  },
  reveal: {
    kicker: 'Mate của anh',
    namePlaceholder: 'Đặt tên cho Mate',
    join: 'Gia nhập Afterburn City',
    back: 'Về Studio',
  },
  joined: {
    headline: 'Chào mừng đến Afterburn City.',
    subline: 'Của anh, và không thể nhầm với bất kỳ ai trong dòng này.',
    restart: 'Bắt đầu lại',
  },
  errors: {
    badImage: 'Không thể đọc ảnh này. Hãy thử JPG hoặc PNG.',
    emptyInput: 'Hãy mô tả anh hoặc thêm ảnh trước.',
    generic: 'Có gì đó trục trặc. Anh thử lại nhé.',
  },
} as const;
